-- Run this script in the Supabase SQL Editor to set up your tables

-- 1. Jobs Table
CREATE TABLE jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_title TEXT NOT NULL,
  department TEXT NOT NULL,
  job_description TEXT NOT NULL,
  salary_grade TEXT,
  qualifications TEXT NOT NULL,
  required_documents TEXT NOT NULL,
  deadline DATE NOT NULL,
  status TEXT DEFAULT 'Open' CHECK (status IN ('Open', 'Closed', 'Archived')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Applications Table
CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES jobs(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  address TEXT NOT NULL,
  status TEXT DEFAULT 'Unread' CHECK (status IN ('Unread', 'Viewed', 'Archived')),
  submitted_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Application Documents Table
CREATE TABLE application_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT REFERENCES applications(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_size BIGINT NOT NULL,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_documents ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies
-- Allow anyone to view jobs
CREATE POLICY "Public jobs are viewable by everyone" ON jobs FOR SELECT USING (true);

-- Allow anyone to submit an application
CREATE POLICY "Anyone can submit applications" ON applications FOR INSERT WITH CHECK (true);

-- Allow anyone to upload application documents info
CREATE POLICY "Anyone can submit documents" ON application_documents FOR INSERT WITH CHECK (true);

-- Instructions for Storage:
-- 1. Go to Storage in Supabase Dashboard
-- 2. Create a new bucket named 'documents'
-- 3. Make sure it is Public or set appropriate policies
-- 4. Policy for Storage:
--    - Name: "Public Uploads"
--    - Allowed operations: SELECT, INSERT
--    - Target bucket: "documents"
